server:
    port: 5213

logging:
  level:
    ROOT: INFO
    org:
      springframework:
        web: TRACE

spring:
  mvc:
    log-request-details: true
  h2:
    console:
        enabled: true
  flyway:
        enabled: false
  datasource:
    instrument:
        jdbcUrl: jdbc:h2:file:/tmp/openexchange/instrument
        username: OE
        password: OEpassword
        driverClassname: org.h2.Driver
    id:
        jdbcUrl: jdbc:h2:file:/tmp/openexchange/id
        username: OE
        password: OEpassword
        driverClassname: org.h2.Driver
    customer:
        jdbcUrl: jdbc:h2:file:/tmp/openexchange/customer
        username: OE
        password: OEpassword
        driverClassname: org.h2.Driver
    order:
        jdbcUrl: jdbc:h2:file:/tmp/openexchange/order
        username: OE
        password: OEpassword
        driverClassname: org.h2.Driver
    url: jdbc:h2:mem:testdb
openexchange:
    database:
        order:
            jdbcUrlTemplate: jdbc:h2:file:/tmp/openexchange/order
            shardCount: 4
            migrationsLocation: database/migrations/order
           # repair: true
        instrument:
            migrationsLocation: database/migrations/instrument
           # repair: true
        id:
            migrationsLocation: database/migrations/id
           # repair: true
        customer:
            migrationsLocation: database/migrations/customer
           # repair: true
    marketDataPublisher:
        numberOfLevelsToPublish: 5
        multicastGroup: 227.3.3.3
        depthPort: 3434
        tradePort: 3436
        interfaceAddress: wotke.danapple.com

